- name: Config Chapter 4 Lab 3
  hosts: target
  tasks:
    - name: clean dnf cache
      ansible.builtin.shell:
        cmd: dnf clean all
      become: true
    - name: run dnf updates and save output
      ansible.builtin.shell:
        cmd: dnf update -y > /root/updates.txt
      become: true
    - name: Notice some updates and some installed
      ansible.builtin.shell:
        cmd: grep -i update /root/updates.txt; grep -i install /root/updates.txt