- name: Config Chapter 3 Lab 4
  hosts: target
  tasks:
    - name: Back up /etc/hosts
      ansible.builtin.shell:
        cmd: cp /etc/hosts /root/etc-hosts-$(date +%s)
    - name: Add hosts entry
      ansible.builtin.shell:
        cmd: echo "{{ tester_ip }} tester" >> /etc/hosts
    - name: Test ping IP and hostname
      ansible.builtin.shell:
        cmd: ping -c 4 {{ tester_ip }}; ping -c 4 tester

- name: Config other hosts 
  hosts: target2
  tasks:
    - name: Back up /etc/hosts
      ansible.builtin.shell:
        cmd: cp /etc/hosts /root/etc-hosts-$(date +%s)
    - name: Add hosts entry
      ansible.builtin.shell:
        cmd: echo "{{ server_ip }} server" >> /etc/hosts
    - name: Test ping IP and hostname
      ansible.builtin.shell:
        cmd: ping -c 4 {{ server_ip }}; ping -c 4 server